import type { Doctor } from "./types";

export const sampleDoctors: Doctor[] = [
  {
    id: "1",
    name: "Prof. Dr Abu Sayeed",
    specialization: "Specialized in Medicine",
    workplace: "Currently sit at Dhaka Medical College",
    phone: "01799499092",
    country: "Bangladesh",
    city: "Dhaka",
    area: "Dhaka Medical",
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop",
    latitude: 23.7272,
    longitude: 90.3855,
    distanceKm: 2.3,
    totalViews: 1247,
    recommendationCount: 89,
    transportOptions: [
      { mode: "car", label: "Car", timeMinutes: 8, cost: "৳80" },
      { mode: "transit", label: "Bus/CNG", timeMinutes: 18, cost: "৳25" },
      { mode: "bike", label: "Bike", timeMinutes: 12, cost: "৳15" },
      { mode: "walk", label: "Walk", timeMinutes: 28 },
    ],
  },
  {
    id: "2",
    name: "Dr. Fatima Rahman",
    specialization: "Cardiology",
    workplace: "Square Hospital, Dhaka",
    phone: "01812345678",
    country: "Bangladesh",
    city: "Dhaka",
    area: "Dhanmondi",
    imageUrl: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=200&h=200&fit=crop",
    latitude: 23.7462,
    longitude: 90.376,
    distanceKm: 5.1,
    totalViews: 892,
    recommendationCount: 72,
    transportOptions: [
      { mode: "car", label: "Car", timeMinutes: 16, cost: "৳150" },
      { mode: "transit", label: "Bus/CNG", timeMinutes: 25, cost: "৳40" },
      { mode: "bike", label: "Bike", timeMinutes: 22, cost: "৳30" },
      { mode: "walk", label: "Walk", timeMinutes: 62 },
    ],
  },
  {
    id: "3",
    name: "Dr. Karim Ahmed",
    specialization: "Orthopedics",
    workplace: "Apollo Hospital, Dhaka",
    phone: "01987654321",
    country: "Bangladesh",
    city: "Dhaka",
    area: "Bashundhara",
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop",
    latitude: 23.8103,
    longitude: 90.4125,
    distanceKm: 8.4,
    totalViews: 654,
    recommendationCount: 54,
    transportOptions: [
      { mode: "car", label: "Car", timeMinutes: 22, cost: "৳220" },
      { mode: "transit", label: "Bus/CNG", timeMinutes: 35, cost: "৳55" },
      { mode: "bike", label: "Bike", timeMinutes: 32, cost: "৳45" },
    ],
  },
  {
    id: "4",
    name: "Dr. Nasrin Akter",
    specialization: "Pediatrics",
    workplace: "United Hospital, Dhaka",
    phone: "01711223344",
    country: "Bangladesh",
    city: "Dhaka",
    area: "Gulshan",
    imageUrl: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200&h=200&fit=crop",
    latitude: 23.7806,
    longitude: 90.4192,
    distanceKm: 1.2,
    totalViews: 1103,
    recommendationCount: 96,
    transportOptions: [
      { mode: "car", label: "Car", timeMinutes: 5, cost: "৳50" },
      { mode: "transit", label: "Bus/CNG", timeMinutes: 12, cost: "৳20" },
      { mode: "walk", label: "Walk", timeMinutes: 15 },
      { mode: "bike", label: "Bike", timeMinutes: 6, cost: "৳10" },
    ],
  },
  {
    id: "5",
    name: "Dr. Hasan Mahmud",
    specialization: "Dermatology",
    workplace: "Ibn Sina Hospital, Dhaka",
    phone: "01555666777",
    country: "Bangladesh",
    city: "Dhaka",
    area: "Mirpur",
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&h=200&fit=crop",
    latitude: 23.8047,
    longitude: 90.3684,
    distanceKm: 6.7,
    totalViews: 521,
    recommendationCount: 41,
    transportOptions: [
      { mode: "car", label: "Car", timeMinutes: 20, cost: "৳180" },
      { mode: "transit", label: "Bus/CNG", timeMinutes: 30, cost: "৳45" },
      { mode: "bike", label: "Bike", timeMinutes: 28, cost: "৳35" },
    ],
  },
];
